# Generated by Django 4.2.15 on 2024-08-09 03:04

from django.db import migrations

def create_staff_counter(apps, schema_editor):
    StaffCounter = apps.get_model('carebridge', 'StaffCounter')
    StaffCounter.objects.create(name="staff_id", value=0)

class Migration(migrations.Migration):

    dependencies = [
        ('carebridge', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(create_staff_counter),
    ]
