# Generated by Django 4.2.15 on 2024-08-15 12:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carebridge', '0002_setup_staff_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card_cvc',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_expiry',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_number',
        ),
        migrations.AddField(
            model_name='contactnote',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facility',
            name='contact_person',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='email_domain',
            field=models.CharField(default='example.com', max_length=50, validators=[django.core.validators.EmailValidator(message='Enter a valid domain')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='carerecord',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge.staff', to_field='staff_id'),
        ),
        migrations.AlterField(
            model_name='carerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge.user', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='contactnote',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge.staff', to_field='staff_id'),
        ),
        migrations.AlterField(
            model_name='contactnote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge.user', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge.user', to_field='user_id'),
        ),
    ]
