# Generated by Django 4.2.15 on 2024-08-22 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carebridge', '0002_plan_facility_is_active_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage_and_usage', models.TextField()),
                ('pharmacy_name', models.CharField(max_length=255)),
                ('pharmacy_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge.staff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge.user')),
            ],
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
