# Generated by Django 4.2.15 on 2024-08-09 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carebridge', '0002_setup_staff_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carerecord',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge.staff', to_field='staff_id'),
        ),
        migrations.AlterField(
            model_name='carerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge.user', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='contactnote',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge.staff', to_field='staff_id'),
        ),
        migrations.AlterField(
            model_name='contactnote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge.user', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge.user', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
