# Generated by Django 4.2.15 on 2024-08-16 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carebridge', '0003_remove_payment_card_cvc_remove_payment_card_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carerecord',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge.staff'),
        ),
        migrations.AlterField(
            model_name='carerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge.user'),
        ),
        migrations.AlterField(
            model_name='contactnote',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge.staff'),
        ),
        migrations.AlterField(
            model_name='contactnote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge.user'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carebridge.user'),
        ),
    ]
