# Generated by Django 4.2.15 on 2024-08-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carebridge', '0003_prescription_delete_medicalrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='plan',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
