# Generated by Django 4.2.15 on 2024-09-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carebridge', '0004_remove_payment_plan_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_method_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
